### PR TITLE
[WIP] Add latex printer

### PR DESCRIPTION
**Pull request by clecat**
Hello,

This PR's goal is to add a printer for `latex` output.
I'm not really sure this is something we want, but it could be useful, tell me what you think of it.

For now the implementations are empty, as I'm no latex expert, I'll try to do my best in order to fill them, but advice are always welcome.

To do:
- [x] document
- [x] attributes
- [x] block
- [x] paragraph
- [x] blockquote
- [x] list
- [x] code_block
- [x] thematic_break
- [x] html_block
- [x] heading
- [x] def_list
- [x] tag_block
- [x] inline
- [x] concat
- [x] text
- [x] emph
- [x] code
- [x] hard_break
- [x] soft_break
- [x] html
- [x] link
- [x] ref
- [x] tag

### CODE REVIEW

**Comment by clecat** [comment]
I added in the last commit a first implementation of the printer, using the output of pandoc and what seemed to me to be a common way of doing things.

However there may be several problems with escaping for example or simply wrong /not optimal implementations.

Reviews from someone with more knowledge of `latex` would be really appreciated.

**Comment by nojb** [comment]
This looks useful. It doesn't apply anymore to `master` because I got rid of the `printer` type in preparation for to 2.0. But let's discuss on Tuesday about this as well, and whether we want to have this in for 2.0 or we leave it for after.

**Comment by nojb** [comment]
As discussed: this is delayed until after the release.

**Comment by shonfeder** [comment]
We'll revisit this once we've settled the current AST. If @clecat is interested in updating the PR to work with all the changes that have been added subsequently, we'll provide whatever support we can. If not, I'll plan to do the integration work myself.

Thanks for your patience here!

**Pull request closed without merging**
