### PR TITLE
Corrected compilation issues in tests, disabled broken tests

### PR DESCRIPTION
**Pull request by clecat**
This is a small pull request solving the problems mentioned (here)[https://github.com/ocaml/omd/issues/178]:
- The compilation errors have been solved, updating the code to the latest version.
- I commented the broken test linked to the absence of implementation
- I added a runtest_all rule (call it with ` dune build @runtest_all `) which launches every test (even the broken one mentioned before).

### CODE REVIEW

**Comment by nojb** [comment]
LGTM. I will look to get the CI enabled again since that will help for future PRs.

**Comment by nojb** [comment]
@avsm has re-enabled the CI for this repository, so future PRs will benefit from the changes you just made here. Thanks!

**Comment by clecat** [comment]
No problem :) One thing to keep in mind though (I just saw it), the dune.inc files are generated, which means that the changes I did will not be kept after a refresh. I will try to solve it later so the changes are permanent (keeping somewhere a blacklist of unit tests or something like that), but it does not seems urgent, as apparently the files were only generated once since the beginning

**Comment by nojb** [comment]
> No problem :) One thing to keep in mind though (I just saw it), the dune.inc files are generated, which means that the changes I did will not be kept after a refresh. I will try to solve it later so the changes are permanent (keeping somewhere a blacklist of unit tests or something like that), but it does not seems urgent, as apparently the files were only generated once since the beginning

Indeed, that file is only regenerated when importing the commonmark test suite, which does not happen very often. So yes, we can leave this for later.

**Pull request merged**
